HeritageAllianceApp/Controllers/FamilyMemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HeritageAllianceApp.Models;

namespace HeritageAllianceApp.Controllers
{
    // CRUD for any family members related to deceased.

    public class FamilyMemberController : Controller
    {
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        //
        // GET: /FamilyMember/

        public ActionResult Index()
        {
            var familymembers = _db.FamilyMembers.Include(f => f.Deceased);
            return View(familymembers.ToList());
        }

        //
        // GET: /FamilyMember/Details/5

        public ActionResult Details(int did, int id = 0)
        {
            FamilyMember familymember = _db.FamilyMembers.Find(id);
            if (familymember == null)
            {
                return HttpNotFound();
            }
            ViewBag.did = did;
            return View(familymember);
        }

        //
        // GET: /FamilyMember/Create

        public ActionResult Create(int did)
        {
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View();
        }

        //
        // POST: /FamilyMember/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FamilyMember familymember, int did)
        {
            if (ModelState.IsValid)
            {
                _db.FamilyMembers.Add(familymember);
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }

            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(familymember);
        }

        //
        // GET: /FamilyMember/Edit/5

        public ActionResult Edit(int did, int id = 0)
        {
            FamilyMember familymember = _db.FamilyMembers.Find(id);
            if (familymember == null)
            {
                return HttpNotFound();
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(familymember);
        }

        //
        // POST: /FamilyMember/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FamilyMember familymember, int did)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(familymember).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(familymember);
        }

        //
        // GET: /FamilyMember/Delete/5

        public ActionResult Delete(int did, int id = 0)
        {
            FamilyMember familymember = _db.FamilyMembers.Find(id);
            if (familymember == null)
            {
                return HttpNotFound();
            }
            ViewBag.did = did;
            return View(familymember);
        }

        //
        // POST: /FamilyMember/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int did)
        {
            FamilyMember familymember = _db.FamilyMembers.Find(id);
            _db.FamilyMembers.Remove(familymember);
            _db.SaveChanges();
            return RedirectToAction("Details", "Deceased", new { id = did });
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HeritageAllianceApp/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HeritageAllianceApp.Models;

namespace HeritageAllianceApp.Controllers
{
    // Crud for records. See ERD.
    public class RecordController : Controller
    {
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        //
        // GET: /Record/

        public ActionResult Index()
        {
            var records = _db.Records.Include(r => r.Deceased);
            return View(records.ToList());
        }

        //
        // GET: /Record/Details/5

        public ActionResult Details(int did, int id = 0)
        {
            Record record = _db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            ViewBag.did = did;
            return View(record);
        }

        //
        // GET: /Record/Create

        public ActionResult Create(int did)
        {
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View();
        }

        //
        // POST: /Record/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Record record, int did)
        {
            if (ModelState.IsValid)
            {
                _db.Records.Add(record);
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }

            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(record);
        }

        //
        // GET: /Record/Edit/5

        public ActionResult Edit(int did, int id = 0)
        {
            Record record = _db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(record);
        }

        //
        // POST: /Record/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Record record, int did)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(record).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.did = did;
            return View(record);
        }

        //
        // GET: /Record/Delete/5

        public ActionResult Delete(int did, int id = 0)
        {
            Record record = _db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            ViewBag.did = did;
            return View(record);
        }

        //
        // POST: /Record/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int did, int id)
        {
            Record record = _db.Records.Find(id);
            _db.Records.Remove(record);
            _db.SaveChanges();
            return RedirectToAction("Details", "Deceased", new { id = did });
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HeritageAllianceApp/Controllers/RelatedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HeritageAllianceApp.Models;

namespace HeritageAllianceApp.Controllers
{
    // Crud to handle relations between deceased.
    public class RelatedController : Controller
    {
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        public ActionResult Index()
        {
            var related = _db.Related.Include(r => r.Deceased).Include(r => r.DeceasedRelative);
            return View(related.ToList());
        }

        public ActionResult Admin()
        {            
            return View(_db.Related.ToList());
        }

        public ActionResult Details(int id = 0)
        {
            Related related = _db.Related.Find(id);
            if (related == null)
            {
                return HttpNotFound();
            }
            return View(related);
        }

        public ActionResult Create(int did)
        {
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.DeceasedRelativeId = new SelectList(deceased, "DeceasedId", "DeceasedName");
            ViewBag.did = did;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Related related, int did)
        {
            if (ModelState.IsValid)
            {
                _db.Related.Add(related);
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }

            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName");
            ViewBag.DeceasedRelativeId = new SelectList(deceased, "DeceasedId", "DeceasedName");
            ViewBag.did = did;
            return View(related);
        }

        public ActionResult Edit(int did, int rid, int id = 0)
        {
            Related related = _db.Related.Find(id);
            if (related == null)
            {
                return HttpNotFound();
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName", did);
            ViewBag.DeceasedRelativeId = new SelectList(deceased, "DeceasedId", "DeceasedName", rid);
            ViewBag.did = did;
            return View(related);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Related related, int did)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(related).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", "Deceased", new { id = did });
            }
            var deceased = _db.Deceased
                               .ToList()
                               .Select(d => new
                               {
                                   DeceasedId = d.DeceasedId,
                                   DeceasedName = string.Format("{0} {1} {2}", d.FirstName, d.MiddleName, d.LastName)
                               });
            ViewBag.DeceasedId = new SelectList(deceased, "DeceasedId", "DeceasedName");
            ViewBag.DeceasedRelativeId = new SelectList(deceased, "DeceasedId", "DeceasedName");
            ViewBag.did = did;
            return View(related);
        }

        public ActionResult Delete(int did, int id = 0)
        {
            Related related = _db.Related.Find(id);
            if (related == null)
            {
                return HttpNotFound();
            }
            ViewBag.did = did;
            return View(related);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int did, int id)
        {
            Related related = _db.Related.Find(id);
            _db.Related.Remove(related);
            _db.SaveChanges();
            return RedirectToAction("Details", "Deceased", new { id = did });
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HeritageAllianceApp/Views/Deceased/DetailsAdmin.cshtml
@model HeritageAllianceApp.Models.Deceased
@using HeritageAllianceApp.Models
@{ HeritageAllianceAppDb _db = new HeritageAllianceAppDb(); }

@{
    ViewBag.Title = "Details";
}

<h2>Details @Html.ActionLink("Edit", "Edit", new { id = ViewBag.did }, new { @class = "btn btn-warning" })</h2>

<fieldset>
    <legend>Deceased</legend>
    <table class="table table-borderless">
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.LastName)
            </th>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayFor(model => model.FirstName)
            </td>
            <td class="display-label">
                @Html.DisplayFor(model => model.MiddleName)
            </td>
            <td class="display-label">
                @Html.DisplayFor(model => model.LastName)
            </td>
        </tr>
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.DateOfDeath)
            </th>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayFor(model => model.DateOfBirth)
            </td>
            <td class="display-label">
                @Html.DisplayFor(model => model.DateOfDeath)
            </td>
        </tr>
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.RowNumber)
            </th>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.LocationWithinRow)
            </th>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.TypeOfBurial)
            </th>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayFor(model => model.RowNumber)
            </td>
            <td class="display-label">
                @Html.DisplayFor(model => model.LocationWithinRow)
            </td>
            <td class="display-label">
                @Html.DisplayFor(model => model.TypeOfBurial)
            </td>
        </tr>
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.StoneDescription)
            </th>
        </tr>
        <tr>
            <td class="display-field">
                @Html.DisplayFor(model => model.StoneDescription)
            </td>
        </tr>
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.MarkerText)
            </th>
        </tr>
        <tr>
            <td class="display-field">
                @Html.DisplayFor(model => model.MarkerText)
            </td>
        </tr>
        <tr>
            <th class="display-label">
                @Html.DisplayNameFor(model => model.MarkerSymbols)
            </th>
        </tr>
        <tr>
            <td class="display-field">
                @Html.DisplayFor(model => model.MarkerSymbols)
            </td>
        </tr>
    </table>
    
    <h2>Deceased Relatives @Html.ActionLink("Create New", "Create", "Related", new { did = ViewBag.did }, new { @class = "btn btn-info" })</h2>
    
    @if (ViewBag.Relatives.Count == 0)
    {
        <p>No deceased relatives found in database.</p>
    }
    else
    {
        <table class="table table-borderless">
            <tr>
                <th class="display-label">
                    @Html.DisplayNameFor(Deceased => Deceased.FirstName)
                </th>
                <th class="display-label">
                    @Html.DisplayNameFor(Deceased => Deceased.MiddleName)
                </th>
                <th class="display-label">
                    @Html.DisplayNameFor(Deceased => Deceased.LastName)
                </th>
                <th class="display-label">
                    Relationship
                </th>
                <th class="display-label">
                    Cemetery Name
                </th>
                <th class="display-label">
                </th>
            </tr>
            @foreach (Related rel in ViewBag.Relatives)
            {
                Deceased dec = _db.Deceased.Find(rel.DeceasedRelativeId);
                Cemetery cem = _db.Cemeteries.Find(dec.CemeteryId);
                <tr>
                    <td class="display-field">
                        @Html.DisplayFor(Deceased => dec.FirstName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(Deceased => dec.MiddleName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(Deceased => dec.LastName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(Related => rel.Relationship)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(Cemetery => cem.CemeteryName)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = dec.DeceasedId }, new { @class = "btn btn-success" })
                        @Html.ActionLink("Edit", "Edit", "Related", new { id = rel.RelatedId, did = rel.DeceasedId, rid = rel.DeceasedRelativeId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Delete", "Delete", "Related", new { id = rel.RelatedId, did = rel.DeceasedId }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    } 
    
    
    <h2>Family Members @Html.ActionLink("Create New", "Create", "FamilyMember", new { did = ViewBag.did }, new { @class = "btn btn-info" })</h2>
    
    @if (ViewBag.FamilyMembers.Count == 0)
    {
        <p>No family members found in database.</p>
    }
    else
    {
        <table class="table table-borderless">
            <tr>
                <th class="display-label">
                    @Html.DisplayNameFor(FamilyMember => FamilyMember.FirstName)
                </th>
                <th class="display-label">
                    @Html.DisplayNameFor(FamilyMember => FamilyMember.MiddleName)
                </th>
                <th class="display-label">
                    @Html.DisplayNameFor(FamilyMember => FamilyMember.LastName)
                </th>
                <th class="display-label">
                    Relationship
                </th>
                <th class="display-label">
                </th>
            </tr>
            @foreach (FamilyMember fam in ViewBag.FamilyMembers)
            {
                <tr>
                    <td class="display-field">
                        @Html.DisplayFor(FamilyMember => fam.FirstName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(FamilyMember => fam.MiddleName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(FamilyMember => fam.LastName)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(FamilyMember => fam.Relationship)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "FamilyMember", new { id = fam.FamilyMemberId, did = ViewBag.did }, new { @class = "btn btn-success" })
                        @Html.ActionLink("Edit", "Edit", "FamilyMember", new { id = fam.FamilyMemberId, did = fam.DeceasedId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Delete", "Delete", "FamilyMember", new { id = fam.FamilyMemberId, did = fam.DeceasedId }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    }

    <h2>Records @Html.ActionLink("Create New", "Create", "Record", new { did = ViewBag.did }, new { @class = "btn btn-info" })</h2>
    
    @if (ViewBag.Records.Count == 0)
    {
        <p>No records found in database.</p>
    }
    else
    {
        <table class="table table-borderless">
            <tr>
                <th class="display-label">
                    Type
                </th>
                <th class="display-label">
                    Description
                </th>                
                <th class="display-label">
                    External Link
                </th>
                <th class="display-label">
                </th>
            </tr>

            @{ List<RecordLink> rll = ViewBag.RecordLinks; }

            @foreach (Record rec in ViewBag.Records)
            {
                <tr>
                    <td class="display-field">
                        @Html.DisplayFor(Record => rec.RecordType)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(Record => rec.RecordDescription)
                    </td>
                    <td>
                        @{
                RecordLink reclink = null;
                foreach (RecordLink rl in rll)
                {
                    if (rl == null) { continue; }
                    if (rl.RecordId == rec.RecordId)
                    {
                        reclink = rl;
                        <a href="@reclink.URL">@reclink.LinkTo</a>
                    }
                }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "Record", new { id = rec.RecordId, did = ViewBag.did }, new { @class = "btn btn-success" })
                        @Html.ActionLink("Edit", "Edit", "Record", new { id = rec.RecordId, did = rec.DeceasedId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Delete", "Delete", "Record", new { id = rec.RecordId, did = rec.DeceasedId }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    }

    <h2>Biographical Information @Html.ActionLink("Create New", "Create", "BiographicalInformation", new { did = ViewBag.did }, new { @class = "btn btn-info" })</h2>
    
    @if (ViewBag.BioInformation.Count == 0)
    {
        <p>No biographical information found in database.</p>
    }
    else
    {
        <table class="table table-borderless">
            <tr>
                <th class="display-label">
                    Type
                </th>
                <th class="display-label">
                    Description
                </th>                
                <th class="display-label">
                    External Link
                </th>
                <th class="display-label">
                </th>
            </tr>

            @{ List<InformationLink> ill = ViewBag.InfoLinks; }

            @foreach (BiographicalInformation bio in ViewBag.BioInformation)
            {
                <tr>
                    <td class="display-field">
                        @Html.DisplayFor(BiographicalInformation => bio.BiographicalInformationType)
                    </td>
                    <td class="display-field">
                        @Html.DisplayFor(BiographicalInformation => bio.BiographicalInfoDescription)
                    </td>
                    <td>
                        @{
                InformationLink infolink = null;
                foreach (InformationLink inl in ill)
                {
                    if (inl == null) { continue; }
                    if (inl.InformationId == bio.BiographicalInformationId)
                    {
                        infolink = inl;
                        <a href="@infolink.URL">@infolink.LinkTo</a>
                    }
                }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "BiographicalInformation", new { id = bio.BiographicalInformationId, did = ViewBag.did }, new { @class = "btn btn-success" })
                        @Html.ActionLink("Edit", "Edit", "BiographicalInformation", new { id = bio.BiographicalInformationId, did = bio.DeceasedId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Delete", "Delete", "BiographicalInformation", new { id = bio.BiographicalInformationId, did = bio.DeceasedId }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    }

</fieldset>
<p>    
    @Html.ActionLink("Back to Listing", "Admin", "Deceased", null, new { @class = "btn btn-default" })
</p>