HeritageAllianceApp/Controllers/CemeteryController.cs
using HeritageAllianceApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HeritageAllianceApp.Controllers
{
    // CRUD for a cemetary location.
    public class CemeteryController : Controller
    {
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        public ActionResult Index()
        {
            var model = _db.Cemeteries.AsEnumerable<Cemetery>()
                .OrderBy(c => c.CemeteryName)
                .ToList();  
            return View(model);           
        }

        public ActionResult Admin()
        {
            //var cemeteries = _db.Cemeteries.Include(c => c.Location);
            //return View(cemeteries.ToList());
            return View(_db.Cemeteries.ToList());
        }

        public ActionResult ListByCity(string city, string state)
        {
            ViewBag.City = city;
            ViewBag.State = state;
            var model = _db.Cemeteries
                .Where(c => c.Location.City == city && c.Location.State == state)
                .OrderBy(c => c.CemeteryName)
                .ToList();
            return View(model);  
        }

        public ActionResult ListByCounty(string county, string state)
        {
            ViewBag.County = county;
            ViewBag.State = state;
            var model = _db.Cemeteries
                .Where(c => c.Location.County == county && c.Location.State == state)
                .OrderBy(c => c.CemeteryName)
                .ToList();
            return View(model);
        }

        public ActionResult ListDeceased(int id)
        {
            Cemetery c = _db.Cemeteries.Find(id);
            var model = _db.Deceased
                .Where(d => d.CemeteryId == id)
                .OrderBy(d => d.LastName)
                .ToList();            
            ViewBag.CemeteryName = c.CemeteryName;
            return View(model);
        }
                
        public ActionResult Details(int id = 0)
        {
            Cemetery cemetery = _db.Cemeteries.Find(id);
            if (cemetery == null)
            {
                return HttpNotFound();
            }
            return View(cemetery);
        }

        public ActionResult Create()
        {
            var locations = _db.Locations                               
                               .ToList()
                               .Select(l => new 
                                { 
                                    LocationId = l.LocationId,
                                    CityStateZip = string.Format("{0}, {1}  {2}", l.City, l.State, l.Zip) 
                                });
            ViewBag.LocationId = new SelectList(locations, "LocationId", "CityStateZip");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cemetery cemetery)
        {
            if (ModelState.IsValid)
            {
                _db.Cemeteries.Add(cemetery);
                _db.SaveChanges();
                return RedirectToAction("Admin");
            }

            var locations = _db.Locations
                               .ToList()
                               .Select(l => new
                               {
                                   LocationId = l.LocationId,
                                   CityStateZip = string.Format("{0}, {1}  {2}", l.City, l.State, l.Zip)
                               });
            ViewBag.LocationId = new SelectList(locations, "LocationId", "CityStateZip");
            return View(cemetery);
        }

        public ActionResult Edit(int id = 0)
        {
            Cemetery cemetery = _db.Cemeteries.Find(id);
            if (cemetery == null)
            {
                return HttpNotFound();
            }
            var locations = _db.Locations
                               .ToList()
                               .Select(l => new
                               {
                                   LocationId = l.LocationId,
                                   CityStateZip = string.Format("{0}, {1}  {2}", l.City, l.State, l.Zip)
                               });
            ViewBag.LocationId = new SelectList(locations, "LocationId", "CityStateZip");
            return View(cemetery);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cemetery cemetery)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(cemetery).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Admin");
            }
            var locations = _db.Locations
                               .ToList()
                               .Select(l => new
                               {
                                   LocationId = l.LocationId,
                                   CityStateZip = string.Format("{0}, {1}  {2}", l.City, l.State, l.Zip)
                               });
            ViewBag.LocationId = new SelectList(locations, "LocationId", "CityStateZip");
            return View(cemetery);
        }

        public ActionResult Delete(int id = 0)
        {
            Cemetery cemetery = _db.Cemeteries.Find(id);
            if (cemetery == null)
            {
                return HttpNotFound();
            }
            return View(cemetery);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cemetery cemetery = _db.Cemeteries.Find(id);
            _db.Cemeteries.Remove(cemetery);
            _db.SaveChanges();
            return RedirectToAction("Admin");
        }
        
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

    }
}

HeritageAllianceApp/Controllers/LocationController.cs
using HeritageAllianceApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HeritageAllianceApp.Controllers
{
    public class LocationController : Controller
    {
        // Initialize the DB
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        public ActionResult Index()
        {            
            return View();
        }

        // Admin needs all DB entries to view. Sorting/filtering will be handled by the view.
        public ActionResult Admin()
        {
            return View(_db.Locations.ToList());
        }

        // Gets the cities. There's only one right now, but functionality for multiple cities was requested.
        public ActionResult CityList()
        {
            var model = _db.Locations
                .Select(l => new LocationHandler { City = l.City, State = l.State })
                .Distinct()
                .OrderBy(l => l.City)
                .ToList();                               
            return View(model);
        }

        // Gets all the counties.
        public ActionResult CountyList()
        {
            var model = _db.Locations
                .Select(l => new LocationHandler { County = l.County, State = l.State })
                .Distinct()
                .OrderBy(l => l.County )                 
                .ToList();
            return View(model);
        }

        // The list of the actual cemetaries
        public ActionResult MapList()
        {
            var model = _db.Cemeteries
                .ToList();
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            Location location = _db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }
        
        // CRUD is below
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Location location)
        {
            if (ModelState.IsValid)
            {
                _db.Locations.Add(location);
                _db.SaveChanges();
                return RedirectToAction("Admin");
            }

            return View(location);
        }
        
        public ActionResult Edit(int id = 0)
        {
            Location location = _db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Location location)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(location).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Admin");
            }
            return View(location);
        }

        public ActionResult Delete(int id = 0)
        {
            Location location = _db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = _db.Locations.Find(id);
            _db.Locations.Remove(location);
            _db.SaveChanges();
            return RedirectToAction("Admin");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose(); 
            base.Dispose(disposing);
        }
    }
}

HeritageAllianceApp/Controllers/SearchController.cs
using HeritageAllianceApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HeritageAllianceApp.Controllers
{
    // Handles all search requests.
    public class SearchController : Controller
    {
        // Initialize DB.
        private HeritageAllianceAppDb _db = new HeritageAllianceAppDb();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search()
        {   // Input validation. Needs to be more extensive later.         
            if (Request.Form["cname"] != null)
            {                
                return RedirectToAction("Cemeteries");
            }
            else if (Request.Form["fname"] != null ||
                     Request.Form["mname"] != null ||
                     Request.Form["lname"] != null ||
                     Request.Form["dob"] != null ||
                     Request.Form["dod"] != null)
            {
                
                return RedirectToAction("Deceased");
            }
            else
            {
                return View();
            }
            
        }

        public ActionResult Cemeteries()
        {
            // Get the list of cemetaries based on search.
            string cname = Request.Form["cname"];
            List<Cemetery> cems = _db.Cemeteries
                                     .Where(c => c.CemeteryName.Contains(cname) || cname == string.Empty)
                                     .ToList();
            return View(cems);
        }
        // List deceased based on search.
        public ActionResult Deceased()
        {
            string fname = Request.Form["fname"];
            string mname = Request.Form["mname"];
            string lname = Request.Form["lname"];
            string dob = Request.Form["dob"];
            string dod = Request.Form["dod"];
            List<Deceased> decs = _db.Deceased
                                         .Where(d => d.FirstName.ToLower().Contains(fname.ToLower()) || fname == string.Empty)
                                         .Where(d => d.MiddleName.ToLower().Contains(mname.ToLower()) || mname == string.Empty)
                                         .Where(d => d.LastName.ToLower().Contains(lname.ToLower()) || lname == string.Empty)
                                         .Where(d => d.DateOfBirth.ToLower().Contains(dob.ToLower()) || dob == string.Empty)
                                         .Where(d => d.DateOfDeath.ToLower().Contains(dod.ToLower()) || dod == string.Empty)
                                         .ToList();
            return View(decs);
        }

        // Overwrite garbage collection. Best practice. 
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

    }
}

HeritageAllianceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Heritage Alliance (Green Team)</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrapcss")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <p class="navbar-brand">Heritage Alliance</p>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                    <li><a href="#">Page 3</a></li>
                </ul>
            </div>
        </div>
    </nav>*@
    <body>
        <header>
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#HANavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <span class="navbar-brand">Heritage Alliance</span>
                    </div>
                    <div>
                        <div class="collapse navbar-collapse" id="HANavbar">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("All Cemeteries", "Cemeteries", "Home")</li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        Browse
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        @*<li>@Html.ActionLink("By Name", "Index", "Cemetery")</li>
                                        <li>@Html.ActionLink("By Location", "Index", "Location")</a></li>*@ 
                                        <li>@Html.ActionLink("By City", "CityList", "Location")</a></li>
                                        <li>@Html.ActionLink("By County", "CountyList", "Location")</a></li>
                                        <li>@Html.ActionLink("Map", "MapList", "Location")</a></li>                                             
                                    </ul>
                                </li>
                                <li>@Html.ActionLink("Advanced Search", "Index", "Search")</a></li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("Admin Panel", "Admin", "Home")</li>
                                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            @*<div class="content-wrapper">
                <div class="float-left">
                    @{ //<p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                        string imgpath = "<img src=" + AppDomain.CurrentDomain.BaseDirectory + "Images/heritagelogoblack.png";

                    }
                    <p class="site-title">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/Images/heritagelogoblack.png")" height="80" width="153" />
                        </a>
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>*@
            <div class="wide">                
            </div>
        </header>
        <div id="body"> 
            <div class="page-header">
                <h1>@ViewBag.PageHead <small>@ViewBag.PageHeadSub</small></h1>
            </div>           
            @*@RenderSection("featured", required: false)*@
            @*<section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>*@
            <section class="content-wrapper main-content ">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <h6>&copy; @DateTime.Now.Year - Heritage Alliance (Green Team)</h6>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrapjs")
        @Styles.Render("~/Content/override")
        @RenderSection("scripts", required: false)
    </body>
</html>